### ISSUE TITLE
Alias does not work as intended for dx-connect

### ISSUE THREAD

**Issue by jeme** [dotJEM/angular-tree#12]
dx-connect also parses the expressions leaving us with having to define the alias for prior in two places.

We should store the alias on the root controller and then pull it down.

**Comment by diwu1989** [comment]
please implement this, its useful for us

**Comment by jeme** [comment]
The fix is in the source, but I haven't had the time to create a release... :(

**Comment by jeme** [comment]
should be fixed in v0.2.2
