### ISSUE TITLE
Using angular-tree with ngResource

### ISSUE THREAD

**Issue by funkytaco** [dotJEM/angular-tree#6]
Would it be possible to lazy load a collapsible treeview using ngResource with this module?

I'm going to need to use 5 REST endpoints that rely on the parent,i.e. endpointA.foo is the key for $resource(endpointB.foo?fooA=:fooA), then foo from endpointB is used for the rest.

Essentially:

endpointA.foo -> endpointB.foo?fooA -> endpointC.foo?fooB -> endpointD?fooB

I've gotten endpointA.foo, but not sure the best way to go about doing the rest with this treeview.

Thanks.

**Comment by jeme** [comment]
Check out: http://plnkr.co/edit/YhQ20OEWI8Ff6baYyQgX?p=preview

these directives don't really care how you load nodes, they just react to a recursive model ( be that a tree or something else )...

As the tree grows really big performance could suffer, but from experience the usability suffers far before that (having a tree with 1000+ nodes loaded and folded out at any time seems like a bad idea in any UI)
