### ISSUE TITLE
Performance seems awful, am I doing something wrong?

### ISSUE THREAD

**Issue by troygilbert** [dotJEM/angular-tree#7]
I love the approach you took to solving this problem, but the performance is unbearable, so bad that I'm assuming there's some kind of pathological case going on.

I have a simple data set, about 20 nodes at the top-level with about 5 of those nodes having 1-3 children each. Less than 50 nodes total. And the template I'm recursing has 10-15 divs plus inputs (pretty basic tree-view + grid implementation).

It takes a measurable number of *seconds* to load the page, on the scale of 5-10. When I doubled the data it basically froze the browser (seemed to take much longer than 10-20 seconds, hence why it seemed pathological).

It's not the non-angular-tree HTML as I was using the same layout previously when I was manually unrolling my nested data structures and it loaded virtually instantly. The only other angular markup is ng-model on the input elements, and a single ng-repeat.

I tried using this angular tree solution:

https://github.com/tchatel/angular-treeRepeat

It renders virtually as quickly as the non-angular approach, and so I'll be trying to make it work (even though I prefer your solution's API). I'm just curious if I'm doing something wrong, or if there are any known worst case scenarios I may be tripping over? (Unfortunately, the code is not in a state where I can share specific examples, but it's pretty straightforward.)

**Comment by jeme** [comment]
v0.2.0 has been re-written to use transcludes, this also deprecates the dx-tree and dx-node directives.

Just from observation, it begins to be noticeable around 500 nodes total spread on 3 levels, taking just about a second on my machine, it's seems acceptable up to ~2000 nodes pre-expanded again on 3 levels.

This is with 3 input elements on each node and some bindings to toggle classes and text bindings ect.

I then keept adding nodes on the fly (by expanding) up to 7500 / 500MB og RAM without any issues, obviously if you do this under a single node and then collapse/expand that it falls back into the above observations when using ng-if (which i would advice in most cases)... that is if you save the node state.

But I never intended this to handle such cases.
